## Simulation Generation

This notebook will run simlations of PSDs with varying slopes and oscillation parameters and save the output into files in ./dat/ 

In [1]:
# Set matplotlib for plotting in the notebook
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

from fooof import FOOOF, FOOOFGroup
from fooof.analysis import *
from fooof.utils import trim_spectrum
from fooof.synth import gen_group_power_spectra, param_sampler, gen_power_spectrum

from utils.ratios import *
from utils.sims import *

In [2]:
theta_band = [4,8]
beta_band = [15,30]
n_trials = 100
freq_range = [1,50]

### Varying Slope Generation  

The following cell will generate ratios from PSDs with slopes 0 to 5 in increments of .25

***ASSUMPTIONS:***

Offset = 0 <br>
Theta CF = 6 <br>
Beta CF = 20 <br>
Amp = .5 <br>
BW = 1

In [3]:
# Gathers ratio data from slope 0 to 5
# Offset is assumed 0
res = []
i = 1
#iterates through various slopes
while(i*.25 < 5):
    bg = [0,i*.25]
        
    #100 trails for each treatment and control sim
    freq, power, _ = gen_group_power_spectra(n_trials, freq_range, bg,gen_sample_slope(), nlvs=np.random.uniform(.005,.02)) 
    fg = FOOOFGroup(peak_width_limits=[1,8], min_peak_amplitude=0.05, max_n_peaks=3)
    fg.fit(freq, power)
    res.append(get_group_ratios(fg, theta_band, beta_band))
    i+=1
np.save('./dat/slope_data',res)

We should now have the data from the simulation saved into ./dat directory. The data is in the form of [slope][ratio_method][trial] later during analysis we will take the average of all the trials and end up with [slope][ratio_method]

### Varying Center Frequency
This function will shift the CF of a band of interest throughout the whole band in increments of .1 while keeping the other band stationed at the middle of its respective band.

***ASSUMPTIONS:***

slope = 1 <br>
offset = 0 <br>
Amp = .5 <br>
BW = 1

In [3]:
gen_varying_cf(theta_band, beta_band, 'low', "cf29th test")

In [4]:
data = np.load("dat/cf29th test.npy")
data

array([[[0.38154602, 0.38393743, 0.38506661, ..., 0.38689506,
         0.37982821, 0.38039106],
        [       nan,        nan, 1.02091599, ..., 0.94186067,
                nan,        nan],
        [0.11077143, 0.1114657 , 0.11179353, ..., 0.11232437,
         0.11027271, 0.11043611]],

       [[0.38194044, 0.38647832, 0.38526649, ..., 0.38286835,
         0.38081997, 0.38091532],
        [0.98382853, 0.98061426, 0.98422836, ..., 0.98872431,
         0.99342503, 0.99525728],
        [0.11088593, 0.11220338, 0.11185156, ..., 0.11115533,
         0.11056064, 0.11058832]],

       [[0.38886198, 0.38535157, 0.38336669, ..., 0.38524501,
         0.39078169, 0.38509788],
        [1.00249286, 0.98435804, 0.99731446, ..., 0.99731742,
         1.04235506, 0.97045693],
        [0.11289541, 0.11187626, 0.11130001, ..., 0.11184533,
         0.11345275, 0.11180261]],

       ...,

       [[0.38898583, 0.3846136 , 0.38330743, ..., 0.38749721,
         0.38473013, 0.38668828],
        [1.0072599 , 

### Varying Amplitude

This function will run band ratios across PSDs with varying amplitudes, from 0 to 1.5

***ASSUMPTIONS:***

slope = 1<br>
offset = 0 <br>
CF = center of bands <br>
Amp = varies | Stationary -> .5
BW = 1

In [3]:
gen_varying_amp(theta_band, beta_band, 'low', "amp29th test")

In [4]:
data = np.load("dat/amp29th test.npy")
data

array([[[0.37523995, 0.37432811, 0.37252132, ..., 0.37187072,
         0.37432554, 0.37518011],
        [4.21042846, 4.75616011, 4.88570116, ..., 5.23894002,
         5.49454172, 4.61519107],
        [0.10894063, 0.1086759 , 0.10815135, ..., 0.10796247,
         0.10867516, 0.10892326]],

       [[0.37854894, 0.38452593, 0.37763414, ..., 0.37559887,
         0.37871104, 0.38335322],
        [2.34678435, 2.41979984, 2.40565139, ..., 2.51487611,
         2.58889355, 2.65002895],
        [0.10990131, 0.11163656, 0.10963572, ..., 0.10904483,
         0.10994837, 0.1112961 ]],

       [[0.38045301, 0.38263484, 0.38159842, ..., 0.38090369,
         0.38291526, 0.38374001],
        [1.70199968, 1.71217569, 1.58975009, ..., 1.65702427,
         1.71082457, 1.6963658 ],
        [0.1104541 , 0.11108754, 0.11078664, ..., 0.11058494,
         0.11116895, 0.11140839]],

       ...,

       [[0.43451756, 0.43518519, 0.42891755, ..., 0.4327433 ,
         0.42930895, 0.42589228],
        [0.39537222, 

### Varying BandWidth

This function will run band ratios across PSDs with varying Band Widths, from .2 to 1.2

***ASSUMPTIONS:***

slope = 1<br>
offset = 0 <br>
CF = center of bands <br>
Amp = .5
BW = varies | stationary band -> 1

In [6]:
gen_varying_amp(theta_band, beta_band, 'low', "bw29th test")

In [7]:
data = np.load("dat/amp29th test.npy")
data

array([[[0.37523995, 0.37432811, 0.37252132, ..., 0.37187072,
         0.37432554, 0.37518011],
        [4.21042846, 4.75616011, 4.88570116, ..., 5.23894002,
         5.49454172, 4.61519107],
        [0.10894063, 0.1086759 , 0.10815135, ..., 0.10796247,
         0.10867516, 0.10892326]],

       [[0.37854894, 0.38452593, 0.37763414, ..., 0.37559887,
         0.37871104, 0.38335322],
        [2.34678435, 2.41979984, 2.40565139, ..., 2.51487611,
         2.58889355, 2.65002895],
        [0.10990131, 0.11163656, 0.10963572, ..., 0.10904483,
         0.10994837, 0.1112961 ]],

       [[0.38045301, 0.38263484, 0.38159842, ..., 0.38090369,
         0.38291526, 0.38374001],
        [1.70199968, 1.71217569, 1.58975009, ..., 1.65702427,
         1.71082457, 1.6963658 ],
        [0.1104541 , 0.11108754, 0.11078664, ..., 0.11058494,
         0.11116895, 0.11140839]],

       ...,

       [[0.43451756, 0.43518519, 0.42891755, ..., 0.4327433 ,
         0.42930895, 0.42589228],
        [0.39537222, 